In [1]:
print('Aufgabe 27')

Aufgabe 27


In [14]:
# Algorithmus: Choleskyzerlegung
# Aufgabenteil a)

import numpy as np

A = np.array([[25, 15, -5], [15, 18, 0], [-5, 0, 11]])
D = np.zeros(3)
n, n = A.shape
R = np.zeros((3,3))

for i in range(0, n):
    D[i] = A[i][i]
    for k in range(0, i):
        D[i] = D[i] - R[k][i] * R[k][i]
    if D[i] <= 0:
        print('A nicht positiv definit.')
        break
    else:
        R[i][i] = D[i] ** 0.5
        for j in range(i+1, n):
            R[i][j] = A[i][j]
            for k in range(0, i):
                R[i][j] = R[i][j] - R[k][i] * R[k][j]
            R[i][j] = R[i][j] / R[i][i]


print('R.T =\n', R.T)
print('')
print('R =\n', R)
print('')
print('R.T @ R =\n', R.T.reshape(3,3) @ R.reshape(3,3))
print('')
print('A =\n', A)
print('')
print('Es gilt also: A = R.T @ R')

R.T =
 [[ 5.  0.  0.]
 [ 3.  3.  0.]
 [-1.  1.  3.]]

R =
 [[ 5.  3. -1.]
 [ 0.  3.  1.]
 [ 0.  0.  3.]]

R.T @ R =
 [[25. 15. -5.]
 [15. 18.  0.]
 [-5.  0. 11.]]

A =
 [[25 15 -5]
 [15 18  0]
 [-5  0 11]]

Es gilt also: A = R.T @ R


In [16]:
# Algorithmus: Choleskyzerlegung
# Aufgabenteil b)

import numpy as np

A = np.array([[9, -3, 0, 3], [-3, 2, -1, -3], [0, -1, 2, 5], [3, -3, 5, 2]])
D = np.zeros(4)
n, n = A.shape
R = np.zeros((4,4))

for i in range(0, n):
    D[i] = A[i][i]
    for k in range(0, i):
        D[i] = D[i] - R[k][i] * R[k][i]
    if D[i] <= 0:
        print('A nicht positiv definit.')
        break
    else:
        R[i][i] = D[i] ** 0.5
        for j in range(i+1, n):
            R[i][j] = A[i][j]
            for k in range(0, i):
                R[i][j] = R[i][j] - R[k][i] * R[k][j]
            R[i][j] = R[i][j] / R[i][i]

print('')
print('R.T =\n', R.T)
print('')
print('R =\n', R)
print('')
print('R.T @ R =\n', R.T.reshape(4,4) @ R.reshape(4,4))
print('')
print('A =\n', A)
print('')
print('Es gilt also: A != R.T @ R')

A nicht positiv definit.

R.T =
 [[ 3.  0.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0. -1.  1.  0.]
 [ 1. -2.  3.  0.]]

R =
 [[ 3. -1.  0.  1.]
 [ 0.  1. -1. -2.]
 [ 0.  0.  1.  3.]
 [ 0.  0.  0.  0.]]

R.T @ R =
 [[ 9. -3.  0.  3.]
 [-3.  2. -1. -3.]
 [ 0. -1.  2.  5.]
 [ 3. -3.  5. 14.]]

A =
 [[ 9 -3  0  3]
 [-3  2 -1 -3]
 [ 0 -1  2  5]
 [ 3 -3  5  2]]

Es gilt also: A != R.T @ R


In [17]:
# Algorithmus: Choleskyzerlegung
# Aufgabenteil c)

import numpy as np

A = np.array([[64, 8, -24, 0, -8], [8, 2, -1, -3, 0], [-24, -1, 29, -2, -3], 
              [0, -3, -2, 11, -2], [-8, 0, -3, -2, 19]])
D = np.zeros(5)
n, n = A.shape
R = np.zeros((5,5))

for i in range(0, n):
    D[i] = A[i][i]
    for k in range(0, i):
        D[i] = D[i] - R[k][i] * R[k][i]
    if D[i] <= 0:
        print('A nicht positiv definit.')
        break
    else:
        R[i][i] = D[i] ** 0.5
        for j in range(i+1, n):
            R[i][j] = A[i][j]
            for k in range(0, i):
                R[i][j] = R[i][j] - R[k][i] * R[k][j]
            R[i][j] = R[i][j] / R[i][i]


print('R.T =\n', R.T)
print('')
print('R =\n', R)
print('')
print('R.T @ R =\n', R.T.reshape(5,5) @ R.reshape(5,5))
print('')
print('A =\n', A)
print('')
print('Es gilt also: A = R.T @ R')

R.T =
 [[ 8.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.]
 [-3.  2.  4.  0.  0.]
 [ 0. -3.  1.  1.  0.]
 [-1.  1. -2.  3.  2.]]

R =
 [[ 8.  1. -3.  0. -1.]
 [ 0.  1.  2. -3.  1.]
 [ 0.  0.  4.  1. -2.]
 [ 0.  0.  0.  1.  3.]
 [ 0.  0.  0.  0.  2.]]

R.T @ R =
 [[ 64.   8. -24.   0.  -8.]
 [  8.   2.  -1.  -3.   0.]
 [-24.  -1.  29.  -2.  -3.]
 [  0.  -3.  -2.  11.  -2.]
 [ -8.   0.  -3.  -2.  19.]]

A =
 [[ 64   8 -24   0  -8]
 [  8   2  -1  -3   0]
 [-24  -1  29  -2  -3]
 [  0  -3  -2  11  -2]
 [ -8   0  -3  -2  19]]

Es gilt also: A = R.T @ R
