In [1]:
print('Aufgabe 13')

Aufgabe 13


In [2]:
# Erste Matrix der 13. Aufgabe

import numpy as np

e = 0.5
b = np.array([[1.0],[2.0]])
A = np.array([[e, 1], [1, 1]])

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[0.5 1. ]
 [1.  1. ]]

A=
 [[ 0.5  1. ]
 [ 0.  -1. ]]
b=
 [[1.]
 [0.]]

Die Lösungen lauten:
x = [ 2. -0.]


In [3]:
# Zweite Matrix der 13. Aufgabe 

import numpy as np

e = 0.5
b = np.array([[2.0],[1.0]])
A = np.array([[1, 1], [e, 1]])

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.  1. ]
 [0.5 1. ]]

A=
 [[1.  1. ]
 [0.  0.5]]
b=
 [[2.]
 [0.]]

Die Lösungen lauten:
x = [2. 0.]


In [4]:
# Fall 1: 0 < e << 1, Erste Matrix

import numpy as np

e = 2 ** (-52)
b = np.array([[1.0],[2.0]])
A = np.array([[e, 1], [1, 1]])

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[2.22044605e-16 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00]]

A=
 [[ 2.22044605e-16  1.00000000e+00]
 [ 0.00000000e+00 -4.50359963e+15]]
b=
 [[ 1.00000000e+00]
 [-4.50359963e+15]]

Die Lösungen lauten:
x = [1. 1.]


In [5]:
# Fall 2: 0 < e << 1, Zweite Matrix

import numpy as np

e = 2 ** (-52)
b = np.array([[2.0],[1.0]])
A = np.array([[1, 1], [e, 1]])

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.00000000e+00 1.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]

A=
 [[1. 1.]
 [0. 1.]]
b=
 [[2.]
 [1.]]

Die Lösungen lauten:
x = [1. 1.]


In [6]:
print('Die Lösungen der beiden Matrizen stimmen überein.')

Die Lösungen der beiden Matrizen stimmen überein.


In [7]:
print('Aufgabe 14')

Aufgabe 14


In [8]:
# Fall 1: n = 3:

import numpy as np

b = np.array([[1.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3], [1/2, 1/3, 1/4], [1/3, 1/4, 1/5]])

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]

A=
 [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03]]
b=
 [[ 1.        ]
 [-0.5       ]
 [ 0.16666667]]

Die Lösungen lauten:
x = [  9. -36.  30.]


In [9]:
# Fall 2: n = 4:

import numpy as np

b = np.array([[1.0], [0.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3, 1/4], [1/2, 1/3, 1/4, 1/5], [1/3, 1/4, 1/5, 1/6], [1/4, 1/5, 1/6, 1/7]])

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]

A=
 [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03  8.33333333e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57142857e-04]]
b=
 [[ 1.        ]
 [-0.5       ]
 [ 0.16666667]
 [-0.05      ]]

Die Lösungen lauten:
x = [  16. -120.  240. -140.]


In [10]:
# Fall 3: n = 5:

import numpy as np

b = np.array([[1.0], [0.0], [0.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3, 1/4, 1/5], [1/2, 1/3, 1/4, 1/5, 1/6],
              [1/3, 1/4, 1/5, 1/6, 1/7], [1/4, 1/5, 1/6, 1/7, 1/8], [1/5, 1/6, 1/7, 1/8, 1/9]])
              

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]

A=
 [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2.00000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02
   6.66666667e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03  8.33333333e-03
   9.52380952e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57142857e-04
   7.14285714e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.26757370e-05]]
b=
 [[ 1.        ]
 [-0.5       ]
 [ 0.16666667]
 [-0.05      ]
 [ 0.01428571]]

Die Lösungen lauten:
x = [   25.  -300.  1050. -1400.   630.]


In [11]:
# Fall 4: n = 6:

import numpy as np

b = np.array([[1.0], [0.0], [0.0], [0.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3, 1/4, 1/5, 1/6], [1/2, 1/3, 1/4, 1/5, 1/6, 1/7],
              [1/3, 1/4, 1/5, 1/6, 1/7, 1/8], [1/4, 1/5, 1/6, 1/7, 1/8, 1/9],
              [1/5, 1/6, 1/7, 1/8, 1/9, 1/10],[1/6, 1/7, 1/8, 1/9, 1/10, 1/11]])
              

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1       ]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909]]

A=
 [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2.00000000e-01  1.66666667e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02
   6.66666667e-02  5.95238095e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03  8.33333333e-03
   9.52380952e-03  9.92063492e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57142857e-04
   7.14285714e-04  9.92063492e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.26757370e-05  5.66893424e-05]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.0000

In [12]:
# Fall 5: n = 7:

import numpy as np

b = np.array([[1.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3, 1/4, 1/5, 1/6, 1/7], [1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8],
              [1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9], [1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10],
              [1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11], [1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12], 
              [1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13]])
              

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125     ]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1       ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308]]

A=
 [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2.00000000e-01  1.66666667e-01  1.42857143e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02
   6.66666667e-02  5.95238095e-02  5.35714286e-02]
 [ 0.00000000e+00 -1.38777878e-17  5.55555556e-03  8.33333333e-03
   9.52380952e-03  9.92063492e-03  9.92063492e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57142857e-04
   7.14285714e-

In [13]:
# Fall 6: n = 8:

import numpy as np

b = np.array([[1.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8], [1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9],
              [1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10], [1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11],
              [1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12], [1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13], 
              [1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14],
              [1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15]])
              

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125     ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1       ]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333 0.07692308]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308 0.07142857]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  0.07142857 0.06666667]]

A=
 [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2.00000000e-01  1.66666667e-01  1.42857143e-01  1.25000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.33333333e-02  7.50000000e-02
   6.66666667e-02  5.95238095e-02  5.35714286e-02  4.86111111e-

In [14]:
# Fall 7: n = 9:

import numpy as np

b = np.array([[1.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9], [1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10],
              [1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11], [1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12],
              [1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13], [1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14], 
              [1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15],
              [1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15, 1/16], 
              [1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15, 1/16, 1/17]])
              

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1       ]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333 0.07692308]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333 0.07692308 0.07142857]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308 0.07142857 0.06666667]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  0.07142857 0.06666667 0.0625    ]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 0.0625     0.05882353]]

A=
 [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01
   2

In [15]:
# Fall 8: n = 10:

import numpy as np

b = np.array([[1.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0]])
A = np.array([[1, 1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10], [1/2, 1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11],
              [1/3, 1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12], [1/4, 1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13],
              [1/5, 1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14], [1/6, 1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15], 
              [1/7, 1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15, 1/16],
              [1/8, 1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15, 1/16, 1/17], 
              [1/9, 1/10, 1/11, 1/12, 1/13, 1/14, 1/15, 1/16, 1/17, 1/18], 
              [1/10, 1/11, 1/12, 1/13, 1/14, 1/15, 1/16, 1/17, 1/18, 1/19]])
              

m, n = A.shape


print(A)

# Nun zum Verfahren: LGS(A|b) lösen, dabei Matrix A in eine obere Dreiecksmatrix bringen
for k in range(1, n):
    for i in range(k, n):
        factor = A[i][k-1] / A[k-1][k-1]
        for j in range(k-1, n):
            A[i][j] += - A[k-1][j] * factor
        b[i] += - b[k-1] * factor


# Rückwärtselimination: Bestimmung der x_i, i = 1,...,n
x = np.zeros(n)
x[n-1] = b[n-1] / A[n-1][n-1]

for i in range(n-2, -1, -1):
    x[i] = b[i]
    for j in range(i+1, n):
        x[i] = x[i] - A[i][j] * x[j]
    x[i] = x[i] / A[i][i]
    
print('')
print('A=\n', A)
print('b=\n', b)
print('')
print('Die Lösungen lauten:')
print('x =', x)

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333 0.07692308 0.07142857]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333 0.07692308 0.07142857 0.06666667]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308 0.07142857 0.06666667 0.0625    ]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  0.07142857 0.06666667 0.0625     0.05882353]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 0.0625     

In [16]:
print('Für n aus {3, 4, 5} sind alle Lösungen von x ganzzahlig. Ab n = 6 existiert mindestens ein Index i, sodass x_i nicht ganzzahlig ist und ab n = 7 sind alle Lösungen x_i nicht ganzzahlig.')

Für n aus {3, 4, 5} sind alle Lösungen von x ganzzahlig. Ab n = 6 existiert mindestens ein Index i, sodass x_i nicht ganzzahlig ist und ab n = 7 sind alle Lösungen x_i nicht ganzzahlig.
