In [18]:
print('Aufgabe 22')

Aufgabe 22


In [47]:
import numpy as np

A = np.array([[1, 2, 0.1, 3, 0.3], [-2, 4, 2, -9.8, 0], [100, 5, 3, 346, 0], 
              [0.5, 9, -0.5, 1.75, 0.3], [2, 6, 6, -0.2, 0], [6, 8, 8, 11.4, 0.3]])
Q = np.eye(6)
R = A

m, m = Q.shape
m, n = A.shape
m, n = R.shape

for k in range(0, m-1):
    x = np.zeros(m)
    for i in range(k, m):
        x[i] = R[i][k]
    g = np.linalg.norm(x)
    v = x
    v[k] = x[k] + g
    s = np.linalg.norm(v)
    if s!=0:
        w = v / s
        u = 2 * R.T.reshape(5,6) @ w.reshape(6,1)
        R = R - w.reshape(6,1) @ u.T.reshape(1,5)
        Q = Q - 2 * Q @ w.reshape(6,1) @ w.T.reshape(1,6)
        

print('Q=\n', Q)
print('')
print('')
print('R=\n', R)
print('')
print('R ist also eine obere Dreiecksmatrix.')
print('')
print('')
print('Q @ R =\n', Q.reshape(6,6) @ R.reshape(6,5))
print('')
print('Es gilt also: Q @ R = A.')
print('')
print('Q @ Q.T=\n', Q @ Q.T)
print('')
print('Q ist also orthogonal.')

Q=
 [[-9.97745150e-03 -1.39259957e-01  1.29788007e-01  6.53712456e-01
  -5.97265837e-01 -4.23787368e-01]
 [ 1.99549030e-02 -2.94447968e-01  2.13139055e-03  6.84085163e-01
   5.32352239e-01  4.01903266e-01]
 [-9.97745150e-01  4.00964154e-02  3.63759669e-02  1.85654661e-02
   3.50503058e-02  6.94733390e-04]
 [-4.98872575e-03 -6.42597861e-01  7.13713334e-01 -2.78668939e-01
  -8.76935755e-14 -6.25422164e-14]
 [-1.99549030e-02 -4.21761885e-01 -4.14028994e-01 -8.74700234e-02
   4.04185460e-01 -6.92301824e-01]
 [-5.98647090e-02 -5.49075802e-01 -5.48653432e-01 -1.37969038e-01
  -4.41905197e-01  4.23787368e-01]]


R=
 [[-1.00225995e+02 -5.57240666e+00 -3.55047611e+00 -3.46132509e+02
  -2.24492659e-02]
 [ 4.44397030e-15 -1.39623882e+01 -7.08441148e+00  9.04151190e+00
  -3.99280086e-01]
 [-3.21231099e-15  0.00000000e+00 -7.10388860e+00  8.03171594e+00
   8.84543728e-02]
 [-1.83693007e-14  0.00000000e+00 -1.36043836e-15 -3.62269621e-01
   7.11223436e-02]
 [ 1.73587535e-14  0.00000000e+00  1.675651

In [40]:
import numpy as np

A = np.array([[1, 21, 0.2, 4.8, 20, 0.2,], [-2, -3, 23, -25.2, -1, 23], [0.3, 4, 21, -20.7, 0, 21], 
              [-0.5, 0.12, 0.56, -1.26, -1, 0.56], [0.7, 0, 0.1, 3.2, 13, 0.1],
              [33, 0.01, 2, 32, 5, 2], [0.14, 0.1, 12, -12.964, 0.13, 12]])
Q = np.eye(7)
R = A

m, m = Q.shape
m, n = A.shape
m, n = R.shape

for k in range(0, m-1):
    x = np.zeros(m)
    for i in range(k, m):
        x[i] = R[i][k]
    g = np.linalg.norm(x)
    v = x
    v[k] = x[k] + g
    s = np.linalg.norm(v)
    if s!=0:
        w = v / s
        u = 2 * R.T.reshape(6,7) @ w.reshape(7,1)
        R = R - w.reshape(7,1) @ u.T.reshape(1,6)
        Q = Q - 2 * Q @ w.reshape(7,1) @ w.T.reshape(1,7)
        


print('Q=\n', Q)
print('')
print('')
print('R=\n', R)
print('')
print('R ist also eine obere Dreiecksmatrix.')
print('')
print('')
print('Q @ R =\n', Q.reshape(7,7) @ R.reshape(7,6))
print('')
print('Es gilt also: Q @ R = A.')
print('')
print('Q @ Q.T=\n', Q @ Q.T)
print('')
print('Q ist also orthogonal.')

Q=
 [[-3.02219698e-02 -9.72348889e-01  2.14330242e-02 -6.56521775e-02
  -2.74183708e-02 -2.19171159e-01 -8.18068212e-03]
 [ 6.04439397e-02  1.36667062e-01 -6.93512405e-01 -2.78181937e-01
   1.81921796e-01 -6.21073892e-01 -2.22638420e-02]
 [-9.06659095e-03 -1.85077214e-01 -6.23088056e-01  1.26057213e-01
   3.01336754e-01  6.86088767e-01 -3.66605976e-03]
 [ 1.51109849e-02 -6.16622754e-03 -1.69702828e-02  6.78628584e-02
   3.14465260e-02 -3.78328032e-02  9.96202827e-01]
 [-2.11553789e-02  8.44278540e-04 -2.48036465e-03 -8.92740867e-01
  -3.21841221e-01  3.03519723e-01  8.27848779e-02]
 [-9.97325005e-01  3.93381050e-02 -3.56982177e-02  2.60209313e-03
   2.01440079e-02 -4.42479837e-02  1.22698429e-02]
 [-4.23107578e-03 -4.46712049e-03 -3.58850859e-01  3.17515018e-01
  -8.77708618e-01  3.75126869e-15 -3.55149720e-16]]


R=
 [[-3.30885116e+01 -8.60842589e-01 -8.45308497e-01 -3.34268599e+01
  -5.94218931e+00 -8.45308497e-01]
 [-6.92726106e-15 -2.15704300e+01 -9.16046757e-01 -2.95298404e+00
  -

In [31]:
print('Aufgabe 23')


Aufgabe 23


In [1]:
import numpy as np

b = np.array([[2.], [4.], [-2.], [10.]])
A = np.array([[1, -0.5, 0.5], [-1, 1, 1], [2, 4, 6], [-2, -4, -4]])
Q = np.eye(4)
R = A

m, m = Q.shape
m, n = A.shape
m, n = R.shape

for k in range(0, m-1):
    x = np.zeros(m)
    for i in range(k, m):
        x[i] = R[i][k]
    g = np.linalg.norm(x)
    v = x
    v[k] = x[k] + g
    s = np.linalg.norm(v)
    if s!=0:
        w = v / s
        u = 2 * R.T.reshape(3,4) @ w.reshape(4,1)
        R = R - w.reshape(4,1) @ u.T.reshape(1,3)
        Q = Q - 2 * Q @ w.reshape(4,1) @ w.T.reshape(1,4)
        

# Rückwärtselimination: Bestimmung der y_i, i = 1,2,3
y = np.zeros(n)
c = Q.T.reshape(4,4) @ b.reshape(4,1)

y[n-1] = c[n-1] / R[n-1][n-1]

for i in range(n-2, -1, -1):
    y[i] = c[i]
    for j in range(i+1, n):
        y[i] = y[i] - R[i][j] * y[j]
    y[i] = y[i] / R[i][i]      

print('Q=\n', Q)
print('')
print('')
print('R=\n', R)
print('')
print('R ist also eine obere Dreiecksmatrix.')
print('')
print('')
print('Q @ R =\n', Q.reshape(4,4) @ R.reshape(4,3))
print('')
print('Es gilt also: Q @ R = A.')
print('')
print('Q @ Q.T=\n', Q @ Q.T)
print('')
print('Q ist also orthogonal.')
print('')
print('')
print('Lösung des LGS Ay=b:')
print('1.Schritt: Bestimme c aus Qc=b:')
print('Qc=b <=> c=Q.T @ b=\n', Q.T.reshape(4,4) @ b.reshape(4,1))
print('')
print('Die Lösung ist y=\n', y)
print('')
print('R @ y =\n', R.reshape(4,3) @ y.reshape(3,1))
print(np.linalg.lstsq(A,b))

Q=
 [[-0.31622777  0.55771224 -0.34179805  0.687118  ]
 [ 0.31622777 -0.70071538 -0.28483171  0.57259833]
 [-0.63245553 -0.31460691 -0.61886162 -0.343559  ]
 [ 0.63245553  0.31460691 -0.64734479 -0.28629917]]


R=
 [[-3.16227766e+00 -4.58530261e+00 -6.16644144e+00]
 [-5.87410441e-16 -3.49642675e+00 -3.56792832e+00]
 [ 3.59998811e-16 -2.79713216e-16 -1.57952130e+00]
 [-7.23707063e-16  5.62308607e-16  6.66133815e-16]]

R ist also eine obere Dreiecksmatrix.


Q @ R =
 [[ 1.  -0.5  0.5]
 [-1.   1.   1. ]
 [ 2.   4.   6. ]
 [-2.  -4.  -4. ]]

Es gilt also: Q @ R = A.

Q @ Q.T=
 [[ 1.00000000e+00 -5.55111512e-17 -2.22044605e-16  4.99600361e-16]
 [-5.55111512e-17  1.00000000e+00  3.88578059e-16 -2.77555756e-16]
 [-2.22044605e-16  3.88578059e-16  1.00000000e+00 -4.02455846e-16]
 [ 4.99600361e-16 -2.77555756e-16 -4.02455846e-16  1.00000000e+00]]

Q ist also orthogonal.


Lösung des LGS Ay=b:
1.Schritt: Bestimme c aus Qc=b:
Qc=b <=> c=Q.T @ b=
 [[ 8.22192192]
 [ 2.08784583]
 [-7.05864763]
 [ 1.4

<ipython-input-1-b6dfe24aa24c>:63: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  print(np.linalg.lstsq(A,b))
